spring:
  application:
    name: eureka-peer

server:
  port: 10000

eureka:
  instance:
    hostname: dev
    instance-id: dev
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:10000/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true
    peer-eureka-nodes-update-interval-ms: 10000

logging:
  level:
    org.springframework.cloud.netflix: debug
    com.netflix: debug
