server:
  port: 8001
spring:
  application:
    name: helloserver




 # 注册示例到 eureka
eureka:
  client:
    service-url:
#      集群配置
#      defaultZone: http://127.0.0.1:10000/eureka/,http://127.0.0.1:10001/eureka/,http://127.0.0.1:10002/eureka/
      defaultZone: http://127.0.0.1:10000/eureka/
